#import "../../templates/course.typ": *

== Extension of fields

For any field $k$, the ring of polynomials in one variable $x$ over $k$ is 
denoted by $k[x]$.
The field of rational functions in one variable $x$ over $k$ is denoted by $k(x)$,
and it consists of all elements of the form $f(x) / g(x)$, where $f(x), g(x) in k[x]$ and $g(x) eq.not 0$.
The field $k(x)$ is the field of fractions of the integral domain $k[x]$.

#defn[
  Let $K$ be a field. A *field extension* of $K$ is a field $L$ that contains $K$ as a subfield. We often denote a field extension by $L slash K$, which indicates that $L$ is an extension of $K$. The field $K$ is called the *base field*, and the field $L$ is called the *extension field*.
]

#example[
  - The field of complex numbers $CC$ is an extension of the field of real numbers $RR$. 
  - Similarly, the field of real numbers $RR$ is an extension of the field of rational numbers $QQ$.
  - For any field $k$, the field of rational functions $k(x)$ in one variable $x$ over $k$ is an extension of $k$.
  - $k((x))$
]

#defn[
  Let $L slash K$ be a field extension. A *subextension* of $L slash K$ is a field $M$ such that $K subset.eq M subset.eq L$. In this case, we say that $M slash K$ is a subextension of $L slash K$.
]

#exer[
  Show that any element of $k(t)$ is a root of some quadratic polynomial with coefficients in $k(t^2)$.
]

== Generated subfields

#defn[
  Let $L slash K$ be a field extension. 
  Let $S$ be a subset of $L$. 
  The *field generated by $S$ over $K$*, denoted by $K(S)$, is defined to be the smallest subfield of $L$ that contains both $K$ and $S$.
  We say that the field extension $L slash K$ is *generated by $S$* if $L = K(S)$.
  The *ring generated by $S$ over $K$*, denoted by $K[S]$, is defined to be the smallest subring of $L$ that contains both $K$ and $S$.
]

#exer[
  Show that $QQ(sqrt(2))$ is equal to $QQ[{sqrt(2)}]$.
]

#exer[
  Show that $QQ(sqrt(2), sqrt(3))$ is equal to $QQ(sqrt(2) + sqrt(3))$.
]

#exer[
  Show that $QQ(sqrt(2), omega)$ is equal to $QQ(sqrt(2) + omega)$, where $omega$ denotes a primitive cube root of unity in $CC$.
]

#remark[
  Note that the field generated by $S$ over $K$ 
  is the intersection of all subfields of $L$ that contain both $K$ and $S$.
  Similarly, the ring generated by $S$ over $K$
  is the intersection of all subrings of $L$ that contain both $K$ and $S$.
]

#defn[
  Let $L slash K$ be a field extension. We say that the extension $L slash K$ is *finitely generated* if there exists a finite subset $S subset L$ such that $L = K(S)$.
]

#exer[
  Let $k$ be a field. Consider the field extension 
  $k(x_1, x_2, dots, x_n) slash k$, where $k(x_1, x_2, dots, x_n)$ is 
  the field of rational functions in $n$ variables $x_1, x_2, dots, x_n$ over $k$. 
  Show that $k(x_1, x_2, dots, x_n)$ is generated by 
  the elements $x_1, x_2, dots, x_n$ over $k$, that is, 
  show that $k(x_1, x_2, dots, x_n) = k({x_1, x_2, dots, x_n})$.
  Also show that the ring $k[x_1, dots, x_n]$ of polynomials 
  in $n$ variables $x_1, dots, x_n$ over $k$ 
  is generated by the elements $x_1, dots, x_n$ over $k$, 
  that is, show that $k[x_1, dots, x_n] = k[{x_1, dots, x_n}]$.
]

#remark[
  The field of rational functions $k(x_1, x_2, dots, x_n)$ in $n$ variables $x_1, x_2, dots, x_n$ over $k$ is the field of fractions of the integral domain $k[x_1, dots, x_n]$ of polynomials in $n$ variables $x_1, dots, x_n$ over $k$.
  Moreover, 
  the field $k(x_1, x_2, dots, x_n)$ is generated by 
  the elements $x_1, x_2, dots, x_n$ over $k$, and hence,  
  the extension $k(x_1, x_2, dots, x_n) slash k$ is finitely generated.
  Furthermore, the ring $k[x_1, dots, x_n]$ is generated by the elements $x_1, dots, x_n$ over $k$.
]

#exer[
  Let $L slash K$ be a field extension, and let $S$ be a subset of $L$. 
  Show that the field generated by $S$ over $K$ is equal to the set of all elements of $L$ that can be expressed as a rational function in the elements of $S$ with coefficients in $K$. In other words, show that
  $
    K(S) = 
    union.big_(S_f subset S, \ |S_f| < infinity) K(S_f)
    .
  $
  Also show that the ring generated by $S$ over $K$ is equal to the set of all elements of $L$ that can be expressed as a polynomial in the elements of $S$ with coefficients in $K$. In other words, show that
  $
    K[S] = 
    union.big_(S_f subset S, \ |S_f| < infinity) K[S_f]
    .
  $
]

#defn[
  Let $L slash K$ be a field extension, 
  and let $alpha_1, alpha_2, dots, alpha_n in L$.
  Then the field $K({alpha_1, alpha_2, dots, alpha_n})$ is denoted by $K(alpha_1, alpha_2, dots, alpha_n)$.
]

== Degree of field extensions

If $L slash K$ is a field extension, then $L$ can be viewed as a vector space over $K$. In particular, we can consider the dimension of $L$ as a vector space over $K$.

#defn[
  Let $L slash K$ be a field extension. We say that $L$ is a *finite extension* of $K$ if $L$ is a finite-dimensional vector space over $K$. In this case, we define the *degree* of the extension $L slash K$ to be the dimension of $L$ as a vector space over $K$, and we denote it by $[L : K]$. If $L$ is not finite-dimensional over $K$, we say that the extension is *infinite*.
]

#exer[
  Show that $k(t) slash k(t^2)$ is a finite extension of degree $2$.
]

#exer[
  Determine the degrees of the following extensions.
  $
    QQ(sqrt(2)) slash QQ,
    QQ(sqrt(2), sqrt(3)) slash QQ,
    QQ(sqrt(2), root(3, 3)) slash QQ,
    QQ(sqrt(2), sqrt(3), sqrt(5)) slash QQ.
  $
]

#exer[
  Let $L slash K$ be a field extension. Show that if $L slash K$ is a finite extension of degree $n$, then any element of $L$ is a root 
  of a polynomial of degree at most $n$ with coefficients in $K$.
]

Now let's look at some examples of finite extensions.

#example[
  Consider the field extension $QQ(sqrt(2)) slash QQ$. We claim that this is a finite extension of degree $2$. To see this, note that any element of $QQ(sqrt(2))$ can be written in the form $a + b sqrt(2)$ for some $a, b in QQ$. The set $B = {1, sqrt(2)}$ is linearly independent over $QQ$, and it spans $QQ(sqrt(2))$, so it forms a basis. Therefore, the dimension of $QQ(sqrt(2))$ as a vector space over $QQ$ is $2$, and we have $[QQ(sqrt(2)) : QQ] = 2$.
]

#lemma[
  Let $L slash K$, $K slash F$ be field extensions. 
  If $L slash K, K slash F$ are finite extensions, then 
  so is $L slash F$, and the degrees of these extensions satisfy
  $ 
  [L : F] = [L : K] [K : F].
  $
]

#proof[
  Note that if the degree of the extension $K slash F$ is infinite, then
  observing that $K$ is an $F$-subspace of $L$,
  it follows that the degree of the extension $L slash F$ is also infinite.
  Also note that if the degree of the extension $L slash K$ is infinite, then
  the degree of the extension $L slash F$ is also infinite, since 
  any subset of $L$ that generates $L$ as a $K$-vector space also generates $L$ as an $F$-vector space.
  This shows that if either $[L : K]$ or $[K : F]$ is infinite, then $[L : F]$ is also infinite.

  Let ${u_1, u_2, dots, u_m}$ be a basis of $L$ over $K$, 
  and let ${v_1, v_2, dots, v_n}$ be a basis of $K$ over $F$. 
  We claim that the set
  $
    B = {u_i v_j : 1 lt.eq i lt.eq m, 1 lt.eq j lt.eq n}
  $ 
  is a basis of $L$ over $F$.
  Indeed, for any $alpha in L$, we can write 
  $
    alpha = sum_(i=1)^m c_i u_i
  $
  for some $c_1, dots, c_m$ lying in $K$.
  Moreover, for each $c_i$, we can write
  $
    c_i = sum_(j=1)^n d_(i j) v_j
  $
  for some $d_(i j)$ lying in $F$.
  This shows that 
  $
    alpha = sum_(i=1)^m sum_(j=1)^n d_(i j) u_i v_j,
  $
  which shows that $B$ generates $L$ over $F$.
  To show that $B$ is linearly independent over $F$, suppose that we have a linear combination
  $
    sum_(i=1)^m sum_(j=1)^n e_(i j) u_i v_j = 0
  $
  for some $e_(i j)$ lying in $F$.
  Then we can rewrite this as
  $
    sum_(i=1)^m (sum_(j=1)^n e_(i j) v_j) u_i = 0.
  $
  Since ${u_1, u_2, dots, u_m}$ is linearly independent over $K$, we must have
  $
    sum_(j=1)^n e_(i j) v_j = 0
  $
  for each $i = 1, dots, m$.
  Since ${v_1, v_2, dots, v_n}$ is linearly independent over $F$, we must have $e_(i j) = 0$ for all $i, j$. This shows that $B$ is linearly independent over $F$, and hence it is a basis of $L$ over $F$. Therefore, we have
  $
    [L : F] = |B| = m n = [L : K] [K : F].
  $
]

#lemma[
  Let $L slash K$ be a field extension, and let $alpha_1, alpha_2, dots, alpha_n in L$. Then the extension $K(alpha_1, alpha_2, dots, alpha_n) slash K$ is finite if and only if each of the extensions $K(alpha_i) slash K$ is finite for $i = 1, dots, n$.
  Moreover, if these extensions are finite, then we have
  $
    [K(alpha_1, alpha_2, dots, alpha_n) : K]
    lt.eq product_(i=1)^n [K(alpha_i) : K]
    .
  $

]

== Algebraic elements and algebraic extensions

#defn[
  Let $L slash K$ be a field extension. An element $alpha in L$ is said to be *algebraic* over $K$ if there exists a non-zero polynomial $f(x) in K[x]$ such that $f(alpha) = 0$. If no such polynomial exists, we say that $alpha$ is *transcendental* over $K$.
]

#exer[
  Is it true that algebraic extensions are finitely generated? If yes, prove it. If not, give a counterexample.
]

#corollary[
  Let $L slash K$ be a field extension,
  and let $alpha$ be an element of $L$. Then
  the following statements are equivalent.
  - The extension $K(alpha) slash K$ is finite.
  - The element $alpha$ is algebraic over $K$.
  Moreover, $alpha$ is algebraic over $K$ if and only if $alpha^n$
  is algebraic over $K$ for some positive integer $n$.
]

#defn[
  Let $L slash K$ be a field extension. If an element $alpha in L$ is algebraic over $K$, then the *minimal polynomial* of $alpha$ over $K$ is the unique monic polynomial $f(x) in K[x]$ of least degree such that $f(alpha) = 0$.
]

#lemma[
  Let $L slash K$ be a field extension, and let $alpha in L$ be algebraic over $K$. Then the following statements hold.
  - The minimal polynomial of $alpha$ over $K$ is irreducible in $K[x]$.
  - If $f(x) in K[x]$ is any polynomial such that $f(alpha) = 0$, then the minimal polynomial of $alpha$ over $K$ divides $f(x)$ in $K[x]$.
  - The degree of the extension $K(alpha) slash K$ is equal to the degree of the minimal polynomial of $alpha$ over $K$.
  - We have 
  $
    K(alpha) = K[alpha].
  $
]

#lemma("Finite extensions are algebraic")[
  Let $L slash K$ be a field extension.
  If $L slash K$ is a finite extension, then 
  $L$ is algebraic over $K$,
  and 
  it is finitely generated as a field extension of $K$.
]

#proposition[
  Let $L slash K$ be a field extension, and let $X$ be a subset of $L$. 
  Assume that every element of $X$ is algebraic over $K$. Then the extension $K(X) slash K$ is algebraic.
  Moreover, if $X$ is finite, then the extension $K(X) slash K$ is finite.
]

#thm[
  Let $L slash K$, $K slash F$ be field extensions. If $L slash K, K slash F$ are algebraic extensions, then so is $L slash F$.
]

#lemma[
  Let $L slash K$ be a field extension. The set of all elements of $L$ that are algebraic over $K$ forms a subfield of $L$, 
  and it is the largest algebraic extension of $K$ contained in $L$.
]

#proof[
  Let $alpha, beta in L$ be algebraic over $K$. 
]

#defn[
  Let $L slash K$ be a field extension. 
  The *algebraic closure* of $K$ in $L$ is the set of all elements of $L$ that are algebraic over $K$. 
  The field extension $L slash K$ is called an *algebraic extension* if every element of $L$ is algebraic over $K$. 
]

== Compositum of field extensions

#defn[
  Let $L_1 slash F$ and $L_2 slash F$ be field extensions, contained in a common extension $K$ of $F$. The *compositum* of $L_1$ and $L_2$ over $F$, denoted by $L_1 L_2$, is defined to be the smallest subfield of $K$ that contains both $L_1$ and $L_2$. In other words, $L_1 L_2$ is the intersection of all subfields of $K$ that contain both $L_1$ and $L_2$.
  The compositum $L_1 L_2$ is also called the *composite field* of $L_1$ and $L_2$ over $F$.
]

#exer[
  Show that if $L_1 slash F$ and $L_2 slash F$ are finite extensions contained in a common extension $K$ of $F$, then the compositum $L_1 L_2 slash F$ is also a finite extension of $F$, and we have
  $
    [L_1 L_2 : F] lt.eq [L_1 : F] [L_2 : F].
  $
  Moreover, if $[L_1 : F]$ and $[L_2 : F]$ are coprime, then we have
  $
    [L_1 L_2 : F] = [L_1 : F] [L_2 : F].
  $
]

== Field homomorphisms and isomorphisms

#exer[
  Let $sigma colon K arrow K$ be a field homomorphism. Show that $sigma$ is injective. 
  Is it true that $sigma$ is surjective? If yes, prove it. If not, give a counterexample.
]